# Generated by Django 4.2.2 on 2023-07-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_executor_alter_task_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
