# Generated by Django 4.2.2 on 2023-07-22 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_relation_task_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='label',
            new_name='labels',
        ),
    ]
