# Generated by Django 4.2.2 on 2023-08-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_label_name'),
        ('tasks', '0006_rename_label_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='tasks.Relation', to='labels.label', verbose_name='Метки'),
        ),
    ]
